language: cpp
compiler:
    - gcc
before_install:
    - sudo apt-get install npm
    - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
    - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
    - "sudo apt-get update"
    - "sudo apt-get install mongodb-org-server"
    - mongod --version
install:
    - sudo pip install -r requirements.txt -r requirements-dev.txt
    - sudo python setup.py install
    - npm install -g grunt grunt-cli
    - npm install
script:
    - mkdir _build
    - cd _build
    - cmake ..
    - ctest -VV -S ../cmake/travis_continuous.cmake
    - cd ..
    - git fetch --unshallow
deploy:
    provider: heroku
    buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
    strategy: git
    api_key:
        secure: RflKHQjdjo4dpebNUGHJrAi4cOchQPtKiA5q9W0iXJ09T2Ad/gZhJqwPN/MKzPb2JTRZzxrVBergjAeTjxcaVbNh97JnC+NBa77A5VFhCDELB2sN/zwjmxpiTtTgDtD8N2MOQcLoc7T8x0TRhk2pANQB3ztrvy+oDX+mq5SbuuU=
    app: girder-test
    on:
        repo: girder/girder
        branch: master
